server:
  port: 8080

spring:
  application:
    name: operations-service
  datasource:
    url: jdbc:postgresql://operations-service-postgres:5432/operations
    username: operations
    password: operations
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
